# Generated by Django 4.1.3 on 2022-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrecipe',
            name='id_dish',
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='sequence_operations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviewrecipe',
            name='dish_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='time_preparation',
            field=models.IntegerField(max_length=5),
        ),
    ]
