# Generated by Django 4.1.3 on 2022-11-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0002_remove_reviewrecipe_id_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrecipe',
            name='difficulty_recipe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='sequence_operations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='time_preparation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewrecipe',
            name='dish_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewrecipe',
            name='rate_recipe',
            field=models.IntegerField(),
        ),
    ]
