# Generated by Django 4.1.3 on 2022-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0003_alter_dishrecipe_difficulty_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrecipe',
            name='dish_name',
        ),
        migrations.AddField(
            model_name='reviewrecipe',
            name='id_dish',
            field=models.IntegerField(null=True),
        ),
    ]
