# Generated by Django 4.1.3 on 2022-11-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0004_remove_reviewrecipe_dish_name_reviewrecipe_id_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrecipe',
            name='id_dish',
            field=models.IntegerField(),
        ),
    ]
