# Generated by Django 4.1.3 on 2022-11-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0005_alter_reviewrecipe_id_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrecipe',
            name='record_date',
            field=models.TextField(null=True),
        ),
    ]
