# Generated by Django 4.1.3 on 2022-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_assistant', '0006_reviewrecipe_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrecipe',
            name='record_date',
            field=models.TextField(),
        ),
    ]
